---
title: "analyzeGainAdapt1Online"
output: html_document
date: "2023-08-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjson)
```

```{r}
save_figs = T
numtrials = 288
trials = 1:288
adapt_trials = rep(1:12, 16) + sort(rep(0:15*18, 12))
test_trials = trials[! trials %in% adapt_trials]
numsubs = 27

sub = vector(length = numsubs * numtrials)
trial = vector(length = numsubs * numtrials)
trial_id = vector(length = numsubs * numtrials) # 1-4; 1= normal short, 2=normal long, 3= vis short, move long, 4 = vis long, move short
phase = vector(length = numsubs * numtrials) #adapt or test
target_angle = vector(length = numsubs * numtrials)
ep_angle = vector(length = numsubs * numtrials)
ep_dist = vector(length = numsubs * numtrials)
too_late = vector(length = numsubs * numtrials)
too_slow = vector(length = numsubs * numtrials)
hit = vector(length = numsubs * numtrials)
rt = vector(length = numsubs*numtrials)
mt = vector(length = numsubs * numtrials)
vis_dist = vector(length = numsubs * numtrials)
move_dist = vector(length = numsubs * numtrials)
extent = vector(length = numsubs * numtrials)

pids = vector(length = numsubs)


df.all = fromJSON(file = "gain-online_e1.json")
c=1
for(s in 1:numsubs){
  print(df.all[[s]]$config$user_agent$browser$name)
  pids[s] = df.all[[s]]$config$id
  for(tt in 1:length(adapt_trials)){
    sub[c] = s
    trial[c] = adapt_trials[tt]
    trial_id[c] = df.all[[s]]$data$adapt[[tt]]$trial_id
    phase[c] = "adapt"
    target_angle[c] = df.all[[s]]$data$adapt[[tt]]$target_angle
    too_late[c] = df.all[[s]]$data$adapt[[tt]]$punish_types | 2
    too_slow[c] = df.all[[s]]$data$adapt[[tt]]$punish_types | 4
    hit[c] = df.all[[s]]$data$adapt[[tt]]$hit
    vis_dist[c] = df.all[[s]]$data$adapt[[tt]]$vis_dist
    move_dist[c] = df.all[[s]]$data$adapt[[tt]]$move_dist
    if(length(df.all[[s]]$data$adapt[[tt]]$reaction_time) == 0){
      rt[c] = NA
      mt[c] = NA
      ep_angle[c] = NA
      ep_dist[c] = NA
      extent[c] = NA
    }
    else{
      rt[c] = df.all[[s]]$data$adapt[[tt]]$reaction_time
      mt[c] = df.all[[s]]$data$adapt[[tt]]$reach_time
      rot_x = c()
      rot_y = c()
      true_move_dist = 0
      for(e in 1:length(df.all[[s]]$data$adapt[[tt]]$movement_data)){
        temp_x = df.all[[s]]$data$adapt[[tt]]$movement_data[[e]]$raw_x
        temp_y = df.all[[s]]$data$adapt[[tt]]$movement_data[[e]]$raw_y
        rot_x[e] = cos(-pi/180 * target_angle[c])*temp_x - sin(-pi/180 * target_angle[c])*temp_y
        rot_y[e] = sin(-pi/180 * target_angle[c])*temp_x + cos(-pi/180 * target_angle[c])*temp_y
        true_move_dist = df.all[[s]]$data$adapt[[tt]]$movement_data[[e]]$cursor_extent #cursor extent computed from raw xy
      }
      #rotate out of 270 as the reference frame
      ep_angle[c] = 180/pi * atan(rot_y[length(rot_y)]/rot_x[length(rot_x)]) 
      extent[c] = true_move_dist
      ep_dist[c] = sqrt((move_dist[c] - rot_x[length(rot_x)])^2 + rot_y[length(rot_y)]^2)
    }
    c= c+1
  }
  for(tt in 1:length(test_trials)){
    sub[c] = s
    trial[c] = test_trials[tt]
    trial_id[c] = df.all[[s]]$data$test[[tt]]$trial_id
    phase[c] = "test"
    target_angle[c] = df.all[[s]]$data$test[[tt]]$target_angle
    too_late[c] = df.all[[s]]$data$test[[tt]]$punish_types | 2
    too_slow[c] = df.all[[s]]$data$test[[tt]]$punish_types | 4
    hit[c] = df.all[[s]]$data$test[[tt]]$hit
    vis_dist[c] = df.all[[s]]$data$test[[tt]]$vis_dist
    move_dist[c] = df.all[[s]]$data$test[[tt]]$move_dist
    if(length(df.all[[s]]$data$test[[tt]]$reaction_time) == 0){
      rt[c] = NA
      mt[c] = NA
      ep_angle[c] = NA
      ep_dist[c] = NA
      extent[c] = NA
    }
    else{
      rt[c] = df.all[[s]]$data$test[[tt]]$reaction_time
      mt[c] = df.all[[s]]$data$test[[tt]]$reach_time
      rot_x = c()
      rot_y = c()
      true_move_dist = 0
      for(e in 1:length(df.all[[s]]$data$test[[tt]]$movement_data)){
        temp_x = df.all[[s]]$data$test[[tt]]$movement_data[[e]]$raw_x
        temp_y = df.all[[s]]$data$test[[tt]]$movement_data[[e]]$raw_y
        rot_x[e] = cos(-pi/180 * target_angle[c])*temp_x - sin(-pi/180 * target_angle[c])*temp_y
        rot_y[e] = sin(-pi/180 * target_angle[c])*temp_x + cos(-pi/180 * target_angle[c])*temp_y
        true_move_dist = df.all[[s]]$data$test[[tt]]$movement_data[[e]]$cursor_extent #cursor extent computed from raw xy
      }
      #rotate out of 270 as the reference frame
      ep_angle[c] = 180/pi * atan(rot_y[length(rot_y)]/rot_x[length(rot_x)]) 
      extent[c] = true_move_dist
      ep_dist[c] = sqrt((move_dist[c] - rot_x[length(rot_x)])^2 + rot_y[length(rot_y)]^2)
    }
    c=c+1
  }
}

dat = data.frame(sub, trial, trial_id, phase, target_angle, ep_angle, ep_dist, rt, mt, too_slow, hit, move_dist, vis_dist, extent)

```

First things first: lets look at a basic learning curve
```{r}
#convert MT and RT to s not ms
if(max(dat$mt, na.rm = T)>10){
  dat$rt = dat$rt/1000
  dat$mt = dat$mt/1000
}
#train = subset(dat, dat$phase == "adapt")
lcs = ddply(dat, .(trial), summarise,
            ha = mean(ep_angle, na.rm = T),
            err = mean(ep_dist, na.rm = T),
            mt.m = mean(mt, na.rm = T))
lcs$acc = lcs$mt.m * lcs$err

ggplot(data = lcs, aes(x = trial, y = ha)) + geom_point() + geom_vline(xintercept = 1+0:16*18, linetype = "dashed")
ggplot(data = lcs, aes(x = trial, y = err)) + geom_point()+ geom_vline(xintercept = 1+0:16*18, linetype = "dashed")
ggplot(data = lcs, aes(x = trial, y = mt.m)) + geom_point()+ geom_vline(xintercept = 1+0:16*18, linetype = "dashed")
ggplot(data = lcs, aes(x = trial, y = acc)) + geom_point()+ geom_vline(xintercept = 1+0:16*18, linetype = "dashed")
```

Main analysis

```{r}

test = subset(dat, dat$phase == "test")
#test$mt[test$mt>1] = NA

for(s in unique(test$sub)){
  test$z_mt[test$sub == s] = (test$mt[test$sub == s]-mean(test$mt[test$sub==s], na.rm = T))/sd(test$mt[test$sub == s], na.rm = T)
}

type_sub = ddply(test, .(sub, trial_id), summarise,
                 mt.m = mean(mt, na.rm = T),
                 err = mean(ep_dist, na.rm = T),
                 ep_var = sd(ep_angle, na.rm = T),
                 move_dist = mean(move_dist, na.rm = T),
                 vis_dist = mean(vis_dist, na.rm = T),
                 md = mean(log(extent), na.rm = T))

type_group = ddply(type_sub, .(trial_id, move_dist, vis_dist), summarise,
                   mt = mean(mt.m, na.rm = T),
                   mt.se = sd(mt.m, na.rm = T)/sqrt(length(mt.m)),
                   dist = mean(md, na.rm = T),
                   dist.se = sd(md, na.rm = T)/sqrt(length(mt.m)),
                   ve = mean(ep_var, na.rm = T),
                   ve.se = sd(ep_var, na.rm = T)/sqrt(length(mt.m)))

ggplot(type_group, aes(x = vis_dist, y = mt, group = move_dist, color = move_dist)) + geom_point(size = 3) + geom_errorbar(width = 0, size = 2, aes(ymin = mt - mt.se, ymax = mt + mt.se))


ggplot(type_group, aes(x = dist, y = mt, group = vis_dist, color = vis_dist)) + geom_point(size = 3)+ geom_errorbar(width = 0, size = 2, aes(ymin = mt - mt.se, ymax = mt + mt.se)) + geom_errorbar(width = 0, size = 2, aes(xmin = dist - dist.se, xmax = dist + dist.se))

ggplot(type_group, aes(x = dist, y = ve, group = vis_dist, color = vis_dist)) + geom_point(size = 3)+ geom_errorbar(width = 0, size = 2, aes(ymin = ve - ve.se, ymax = ve + ve.se)) + geom_errorbar(width = 0, size = 2, aes(xmin = dist - dist.se, xmax = dist + dist.se))

ggplot(type_group, aes(x = vis_dist, y = dist, group = move_dist, color = move_dist)) + geom_point(size = 3)+ geom_errorbar(width = 0, size = 2, aes(ymin = dist - dist.se, ymax = dist + dist.se))


ggplot(type_group, aes(x = move_dist, y = dist, group = vis_dist, color = vis_dist)) + geom_point(size = 3)+ geom_errorbar(width = 0, size = 2, aes(ymin = dist - dist.se, ymax = dist + dist.se))

#linear mixed model as anova
mt_fit = lmer(mt.m ~ md + vis_dist + (1|sub), data = type_sub)
summary(mt_fit)
anova(mt_fit)

ve_fit = lmer(ep_var ~ md + vis_dist + (1|sub), data = type_sub)
anova(ve_fit)

if(save_figs){
  write.csv(type_sub, "E2_MTs.csv")
}
```

Learning blocks
```{r}
#remember, trial id is the trial type
# 1 = normal short
# 2 = normal long
# 3 = vis short, move long
# 4 = vis long, move short
train = subset(dat, dat$phase == "adapt")
train$ti = (train$trial-1)%%18 #trial index within a block

sub_lc = ddply(train, .(sub, trial_id, ti), summarise,
                 mt= mean(mt, na.rm = T),
                 err = mean(ep_dist, na.rm = T),
                 extent_err = mean((extent-move_dist)/move_dist, na.rm = T))

block_lc = ddply(sub_lc, .(ti, trial_id), summarise,
                 mt.m = mean(mt, na.rm = T),
                 mt.se = sd(mt, na.rm = T)/sqrt(length(mt)),
                 err.m = mean(err, na.rm = T),
                 err.se = sd(err, na.rm = T)/sqrt(length(err)),
                 err_e.m = mean(extent_err, na.rm = T),
                 err_e.se = sd(extent_err, na.rm = T)/sqrt(length(extent_err)))

#last trial of the training blocks
last_trial = subset(sub_lc, sub_lc$ti == 11)

ggplot(data = block_lc, aes(x = ti, y = mt.m, group = as.factor(trial_id), color = as.factor(trial_id), fill = as.factor(trial_id))) + geom_point() + geom_ribbon(aes(ymin = mt.m - mt.se, ymax = mt.m+mt.se), alpha = 0.5, color = NA)

ggplot(data = block_lc, aes(x = ti, y = err.m, group = as.factor(trial_id), color = as.factor(trial_id), fill = as.factor(trial_id))) + geom_point() + geom_ribbon(aes(ymin = err.m - err.se, ymax = err.m+err.se), alpha = 0.5, color = NA)

ggplot(data = block_lc, aes(x = ti, y = err_e.m, group = as.factor(trial_id), color = as.factor(trial_id), fill = as.factor(trial_id))) + geom_point() + geom_ribbon(aes(ymin = err_e.m - err_e.se, ymax = err_e.m+err_e.se), alpha = 0.5, color = NA)

#success rates
sub_hit = ddply(train, .(sub, trial_id), summarise,
                hit = mean(hit))
group_hit = ddply(sub_hit, .(trial_id), summarise,
                  hit.m = mean(hit),
                  hit.se = sd(hit)/sqrt(numsubs))
ggplot(data = group_hit, aes(x = trial_id, y = hit.m, group = as.factor(trial_id), color = as.factor(trial_id))) + geom_point(size = 3) + geom_errorbar(aes(ymin = hit.m - hit.se, ymax = hit.m + hit.se), width = 0, size = 2) 

if(save_figs){
  write.csv(sub_hit, "E2_hit_train.csv")
  write.csv(sub_lc, "E2_lc_train.csv")
}

```

Modeling!
```{r}
numtrials = length(test_trials)

mdFitts = function(params, df){
  a = params[1]
  b = params[2]
  pred_mt = a + b*log(df$extent)
  sse = sum((pred_mt-df$mt)^2, na.rm = T)
  return(sse)
}
diffFitts = function(params, df){
  a = params[1]
  b = params[2]
  gain = df$vis_dist/df$move_dist
  pred_mt = a + b*log(df$extent * gain)
  sse = sum((pred_mt-df$mt)^2, na.rm = T)
  return(sse)
}

vdFitts = function(params, df){
  a = params[1]
  b = params[2]
  pred_mt = a + b*log(df$vis_dist)
  sse = sum((pred_mt-df$mt)^2, na.rm = T)
  return(sse)
}

#three params
avgFitts = function(params, df){
  a = params[1]
  b = params[2]
  m = params[3]
  d = m*df$extent + (1-m)*df$vis_dist
  pred_mt = a + b*log(d)
  sse = sum((pred_mt-df$mt)^2, na.rm = T)
  return(sse)
}
diff2Fitts = function(params, df){
  a = params[1]
  b = params[2]
  m = params[3]
  gain = df$vis_dist/df$move_dist
  w_eff = m/gain + (1-m)
  pred_mt = a + b*log(df$extent/w_eff)
  sse = sum((pred_mt-df$mt)^2, na.rm = T)
  return(sse)
}

md_a = vector(length = numsubs)
md_b = vector(length = numsubs)
md_r = vector(length = numsubs)
md_bic = vector(length = numsubs)
diff_a = vector(length = numsubs)
diff_b = vector(length = numsubs)
diff_r = vector(length = numsubs)
diff_bic = vector(length = numsubs)
vd_a = vector(length = numsubs)
vd_b = vector(length = numsubs)
vd_r = vector(length = numsubs)
vd_bic = vector(length = numsubs)

#three params
avg_a = vector(length = numsubs)
avg_b = vector(length = numsubs)
avg_m = vector(length = numsubs)
avg_r = vector(length = numsubs)
avg_bic = vector(length = numsubs)
diff2_a = vector(length = numsubs)
diff2_b = vector(length = numsubs)
diff2_m = vector(length = numsubs)
diff2_r = vector(length = numsubs)
diff2_bic = vector(length = numsubs)


for(s in unique(test$sub)){
  dat.s = subset(test, sub ==s)
  res = optim(c(0.5, 0.5), mdFitts, df = dat.s, method = "L-BFGS-B",
                   lower = c(-1,0), upper = c(1,1))
  md_a[s] = res$par[1]
  md_b[s] = res$par[2]
  md_r[s] = 1-(res$value/sum((dat.s$mt - mean(dat.s$mt, na.rm= T))^2, na.rm = T))
  md_bic[s] = log(numtrials)*length(res$par) + numtrials*log(res$value/numtrials)
  res = optim(c(0.5, 0.5), diffFitts, df = dat.s, method = "L-BFGS-B",
                   lower = c(-1,0), upper = c(1,1))
  diff_a[s] = res$par[1]
  diff_b[s] = res$par[2]
  diff_r[s] = 1-(res$value/sum((dat.s$mt - mean(dat.s$mt, na.rm= T))^2, na.rm = T))
  diff_bic[s] = log(numtrials)*length(res$par) + numtrials*log(res$value/numtrials)
  res = optim(c(0.5, 0.5), vdFitts, df = dat.s, method = "L-BFGS-B",
                   lower = c(-1,0), upper = c(1,1))
  vd_a[s] = res$par[1]
  vd_b[s] = res$par[2]
  vd_r[s] = 1-(res$value/sum((dat.s$mt - mean(dat.s$mt, na.rm= T))^2, na.rm = T))
  vd_bic[s] = log(numtrials)*length(res$par) + numtrials*log(res$value/numtrials)
  
  res = optim(c(0.5, 0.5, 0.5), avgFitts, df = dat.s, method = "L-BFGS-B",
                   lower = c(-1,0, 0), upper = c(1,1,1))
  avg_a[s] = res$par[1]
  avg_b[s] = res$par[2]
  avg_m[s] = res$par[3]
  avg_r[s] = 1-(res$value/sum((dat.s$mt - mean(dat.s$mt, na.rm= T))^2, na.rm = T))
  avg_bic[s] = log(numtrials)*length(res$par) + numtrials*log(res$value/numtrials)
  res = optim(c(0.5, 0.5, 0.5), diff2Fitts, df = dat.s, method = "L-BFGS-B",
                   lower = c(-1,0,0), upper = c(1,1,1))
  diff2_a[s] = res$par[1]
  diff2_b[s] = res$par[2]
  diff2_m[s] = res$par[3]
  diff2_r[s] = 1-(res$value/sum((dat.s$mt - mean(dat.s$mt, na.rm= T))^2, na.rm = T))
  diff2_bic[s] = log(numtrials)*length(res$par) + numtrials*log(res$value/numtrials)
}
```

Plot
```{r}
for(s in unique(test$sub)){
  d = test$extent[test$sub == s]
  vis = test$vis_dist[test$sub == s]
  gain = test$vis_dist[test$sub == s]/test$move_dist[test$sub==s]
  test$md_mt[test$sub == s] = md_a[s] + md_b[s]*log(d)
  test$vd_mt[test$sub == s] = vd_a[s] + vd_b[s]*log(vis)
  test$diff_mt[test$sub == s] = diff_a[s] + diff_b[s]*log(d*gain)
  test$avg_mt[test$sub == s] = avg_a[s] + avg_b[s]*log(avg_m[s]*d + (1-avg_m[s])*vis)
  test$diff2_mt[test$sub == s] = diff2_a[s] + diff2_b[s]*log(d/(diff2_m[s]/gain + (1-diff2_m[s])))
}



type_sub = ddply(test, .(sub, trial_id), summarise,
                 mt.m = mean(mt, na.rm = T),
                 md_mt = mean(md_mt, na.rm = T),
                 vd_mt = mean(vd_mt, na.rm = T),
                 diff_mt = mean(diff_mt, na.rm = T),
                 avg_mt = mean(avg_mt, na.rm = T),
                 diff2_mt = mean(diff2_mt, na.rm = T),
                 move_dist = mean(move_dist, na.rm = T),
                 vis_dist = mean(vis_dist, na.rm = T),
                 md = mean(extent, na.rm = T))


# pseudo-R2s and BICs (on trial type, not individual trials)
avg_r2 = vector(length = numsubs)
md_r2 = vector(length = numsubs)
vd_r2 = vector(length = numsubs)
diff2_r2 = vector(length = numsubs)

avg_bic2 = vector(length = numsubs)
md_bic2 = vector(length = numsubs)
vd_bic2 = vector(length = numsubs)
diff2_bic2 = vector(length = numsubs)
for(s in 1:numsubs){
  mt.s = type_sub$mt.m[type_sub$sub == s]
  avg_r2[s] = 1-(sum((type_sub$avg_mt[type_sub$sub == s] - mt.s)^2)/sum((mt.s - mean(mt.s))^2))
  md_r2[s] = 1-(sum((type_sub$md_mt[type_sub$sub == s] - mt.s)^2)/sum((mt.s - mean(mt.s))^2))
  vd_r2[s] = 1-(sum((type_sub$vd_mt[type_sub$sub == s] - mt.s)^2)/sum((mt.s - mean(mt.s))^2))
  diff2_r2[s] = 1-(sum((type_sub$diff2_mt[type_sub$sub == s] - mt.s)^2)/sum((mt.s - mean(mt.s))^2))
  avg_bic2[s] = 3*log(4) + 4*log(sum((type_sub$avg_mt[type_sub$sub == s] - mt.s)^2)/4)
  md_bic2[s] = 2*log(4) + 4*log(sum((type_sub$md_mt[type_sub$sub == s] - mt.s)^2)/4)
  vd_bic2[s] = 2*log(4) + 4*log(sum((type_sub$vd_mt[type_sub$sub == s] - mt.s)^2)/4)
  diff2_bic2[s] = 3*log(4) + 4*log(sum((type_sub$diff2_mt[type_sub$sub == s] - mt.s)^2)/4)
}

model_fits = data.frame(msi_r2 = avg_r2, msi_bic = avg_bic2, md_r2 = md_r2, md_bic = md_bic2,
                        vd_r2 = vd_r2, vd_bic = vd_bic2, ew_r2 = diff2_r2, ew_bic = diff2_bic2)
if(save_figs){
  write.csv(model_fits, "E2_modelfits.csv")
}

type_group = ddply(type_sub, .(trial_id, move_dist, vis_dist), summarise,
                   mt = mean(mt.m, na.rm = T),
                   mt.se = sd(mt.m, na.rm = T)/sqrt(length(mt.m)),
                   md_mt = mean(md_mt),
                   vd_mt = mean(vd_mt),
                   diff_mt = mean(diff_mt),
                   avg_mt = mean(avg_mt),
                   diff2_mt = mean(diff2_mt),
                   dist = mean(md, na.rm = T),
                   dist.se = sd(md, na.rm = T)/sqrt(length(mt.m)))

ggplot(type_group, aes(x = dist, y = mt, group = vis_dist, color = vis_dist)) + geom_point(size = 3)+ geom_errorbar(width = 0, size = 2, aes(ymin = mt - mt.se, ymax = mt + mt.se)) + geom_errorbar(width = 0, size = 2, aes(xmin = dist - dist.se, xmax = dist + dist.se)) + geom_point(aes(y = diff_mt, group = move_dist), color = "red", size = 3) + geom_point(aes(y = diff2_mt, group = move_dist), color = "green", size = 3) + geom_point(aes(y = avg_mt, group = move_dist), color = "blue", size = 3)
```

Subset prolific csv on only participants who we've got data for
```{r}
demographics = read.csv("e1online_demo.csv")
name_in_list = function(names, ids){ #funny that i did this as a function; its not like anyone could use this
  rows = vector(length = length(names))
  for(r in 1:length(rows)){
    found = FALSE
    for(p in 1:length(ids)){
      found = found | startsWith(names[r], ids[p])
    }
    rows[r] = found
  }
  return(rows)
}
demographics = subset(demographics, name_in_list(demographics$Participant.id, pids))
write.csv(demographics, "e1online_included.csv")
```
